language: python
sudo: false
cache: pip
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
env:
  global:
    - DB_SETTINGS='{"ENGINE":"django.db.backends.postgresql_psycopg2","NAME":"django_cte","USER":"postgres","PASSWORD":"","HOST":"localhost","PORT":""}'
  matrix:
    - REQ="Django>=2.2,<3.0"
    - REQ="Django>=3.0,<3.1"
    - REQ="Django>=3.1,<3.2"
    - REQ="Django>=3.2,<3.3"
    - REQ="https://github.com/django/django/archive/master.zip#egg=Django"
matrix:
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip#egg=Django"
services:
- postgresql
install:
- pip install --upgrade pip wheel
- pip install "$REQ" psycopg2-binary nose flake8
script: nosetests -v && flake8 django_cte/ tests/
